baseURL: 'https://mohamedallam.tech'
title: Mohamed Allam
languageCode: 'en-us'
theme: mohamed

params:
  # basic
  description: My journey cheating on PHP Laravel for Golang, then Elixir become my mistress
  author: Mohamed
  #images:
  #  - preview.png
  favicon: favicon.ico
  #logo:
  #  icon: forge.png
  DateFormat: "2022-01-19"

  # theme params
  DisableLanguageSwitch: true
  TocOpen: true
  TocSide: right
  EnableInstantClick: true
  EnableImageZoom: true
  ShowShareButtons: true
  ShareButtons:
    - twitter
    - telegram
  ShowReadingTime: true
  ShowWordCount: true
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true

  socialIcons:
    - name: linkedin-simple
      url: "https://github.com/mohamedallam1991"
    - name: youtube-simple
      url: "https://github.com/mohamedallam1991"
    - name: github-simple
      url: "https://github.com/mohamedallam1991"
    - name: twitter-simple
      url: "https://twitter.com/mohamedallamorg"
    - name: telegram-simple
      url: "https://t.me/"
    - name: rss-simple
      url: "feed.xml"

languages:
  en:
    languageName: "English"
    homeInfoParams:
      Title: My journey learning to code publicly, documenting the process
      Content: |-
        Hello, I'm **MOHAMED**. Nice to have you here!

menu:
  main:
    - name: Archives
      url: archives
      weight: 1
    - name: Tags
      url: tags
      weight: 2
    - name: Search
      url: search
      weight: 3

outputs:
  home:
    - HTML
    - RSS
    - JSON

outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feed"

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: dracula
    lineNos: false
    noClasses: false
