baseURL: 'https://mohamedallam.tech'
title: Mohamed Allam
languageCode: 'en-us'
theme: PaperModX

params:
  # basic
  description: My journey cheating on PHP Laravel for Golang, then Elixir become my mistress
  author: Mohamed
  #images:
  #  - preview.png
  favicon: favicon.ico
  #logo:
  #  icon: forge.png
  DateFormat: "2006-01-02"

  # theme params
  DisableLanguageSwitch: true
  TocOpen: true
  TocSide: right
  EnableInstantClick: true
  EnableImageZoom: true
  ShowShareButtons: true
  ShareButtons:
    - twitter
    - telegram
  ShowReadingTime: true
  ShowWordCount: true
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true

  socialIcons:
    - name: facebook-simple
      url: "https://facebook.com/mohamedallam1991"
    - name: linkedin-simple
      url: "https://github.com/mohamedallam1991"
    - name: youtube-simple
      url: "https://github.com/mohamedallam1991"
    - name: github-simple
      url: "https://github.com/mohamedallam1991"
    - name: twitter-simple
      url: "https://twitter.com/mohamedallamorg"
    - name: telegram-simple
      url: "https://t.me/"
    - name: rss-simple
      url: "feed.xml"

languages:
  en:
    languageName: "English"
    homeInfoParams:
      Title: My journey learning to code publicly, documenting the process
      Content: |-
        Hello, I'm **MOHAMED**. Nice to have you here!
        Hello, I’m MOHAMED. Nice to have you here! a self-taught Golang programmer who started learning the language in late 2016. Initially, I was looking for a new programming language to learn and decided to try Golang because it seemed to be relatively new and had a lot of potential. Little did I know that this decision would change my life completely. Since then, I’ve been tirelessly working on learning as much about the language as possible and pushing myself to become a better programmer. My passion is teaching and helping others learn programming. So whether you’re a beginner or have some experience, One ore more blog posts can help you get started with Go programmer or other technologies I come across. In addition to tutorials and videos Self taught and passionate web developer, sharing my journey from novice to advanced web developer. I pride myself on being able to teach anyone how to code, and I believe that every individual should have access to the power of coding. My courses are designed for complete beginners, but you can also find tips and tricks for more experienced developers.

menu:
  main:
    - name: Archives
      url: archives
      weight: 1
    - name: Tags
      url: tags
      weight: 2
    - name: Search
      url: search
      weight: 3
    - name: Contact
      url: contact
      weight: 4

outputs:
  home:
    - HTML
    - RSS
    - JSON

outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feed"

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: dracula
    lineNos: false
    noClasses: false
